# Generated by Django 3.0.2 on 2020-01-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='troops',
            field=models.ManyToManyField(related_name='users', to='participant.Troop', verbose_name='troops'),
        ),
    ]
