name: Django application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        CI=1 pipenv --bare install
        python --version ; pip --version ; pipenv --version
    - name: Lint with flake8
      run: |
        CI=1 pipenv --bare install flake8
        # stop the build if there are Python syntax errors or undefined names
        CI=1 pipenv --bare run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude migrations,__pycache__
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        CI=1 pipenv --bare run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude migrations,__pycache__
    - name: Test with manage.py
      run: |
        CI=1 pipenv --bare run python -Wa manage.py test
